name: "build-release"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
    paths:
      - "src/**"
      - "templates/**"
      - "assets/**"
      - "build.rs"
      - "Cargo.toml"
      - "Cargo.lock"
      - "home-api.db"
      - "input.css"
      - "package.json"
      - "package-lock.json"
      - "tailwind.config.js"

jobs:
  release-arm64:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: home-api
    env:
      BRANCH: ${{ github.ref }}
      RETENTION_DAYS: 0
      API_SECRET: just-to-pass-the-build-for-testing

    steps:
      - uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v2
        id: rust-aarch64
        with:
          arch: aarch64
          distro: ubuntu_latest
          base_image: rust:latest
          setup: |
            mkdir -p "${PWD}/artifacts"
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
            -e API_SECRET=${{secrets.API_SECRET}}
          shell: /bin/bash
          run: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
            source ~/.bashrc
            cd home-api
            nvm install 18
            npm install
            npm install npx
            cargo build --release --features vendored
            cp target/release/home-api /artifacts
      
      - name: Set retention for artifacts
        run: |
          if [[ $BRANCH == 'refs/heads/main' ]]; then
            echo "RETENTION_DAYS=90"
          else
            echo "RETENTION_DAYS=3"
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: home-api-arm64
          retention-days: ${{ env.RETENTION_DAYS }}
          path: ./artifacts
