name: "build-release"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
    paths:
      - "src/**"
      - "templates/**"
      - "assets/**"
      - "build.rs"
      - "Cargo.toml"
      - "Cargo.lock"
      - "home-api.db"
      - "input.css"
      - "package.json"
      - "package-lock.json"
      - "tailwind.config.js"

jobs:
  release-arm64:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: home-api
    env:
      BRANCH: ${{ github.ref }}
      RETENTION_DAYS: 0
      API_SECRET: just-to-pass-the-build-for-testing

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu

      - run: sudo apt-get install gcc-aarch64-linux-gnu -y

      - name: Setup Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: home-api/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Install npx
        run: npm install npx

      - run: cargo build --release --target aarch64-unknown-linux-gnu --features vendored
      
      - name: Set retention for artifacts
        run: |
          if [[ $BRANCH == 'refs/heads/main' ]]; then
            echo "RETENTION_DAYS=90"
          else
            echo "RETENTION_DAYS=3"
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: home-api-arm64
          retention-days: ${{ env.RETENTION_DAYS }}
          path: |
            target/aarch64-unknown-linux-gnu/release/home-api
            target/aarch64-unknown-linux-gnu/release/home-api.db
